name: Publish Docker Image

on:
  push:
    branches: [ main ]
  release:
    types:
      - published

env:
  DOCKER_IMAGE_NAME: ghcr.io/Gordiancyber/recipe-stable-diffusion-2-1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      run: |
        mkdir -p ~/.docker/cli-plugins
        curl -SL https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
        chmod a+x ~/.docker/cli-plugins/docker-buildx
        docker buildx create --use --name mybuilder

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx build --push --tag ${DOCKER_IMAGE_NAME}:latest --tag ${DOCKER_IMAGE_NAME}:${GITHUB_SHA} .
